---
- name: Create bastion directory
  ansible.builtin.file:
    path: /opt/bastion
    state: directory
    mode: '0755'

- name: Create docker directory
  ansible.builtin.file:
    path: /opt/bastion/docker
    state: directory
    mode: '0755'

- name: Create docker directory
  ansible.builtin.file:
    path: /opt/bastion/docker/{{ item.name }}
    state: directory
    mode: '0755'
  with_items: "{{ user_list }}"

- name: Create sshpiper directory
  ansible.builtin.file:
    path: /opt/bastion/sshpiper
    state: directory
    mode: '0755'

- name: Copy docker file
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /opt/bastion/docker/{{ item | basename }}
    owner: root
    group: root
    mode: '0644'
  with_fileglob:
    - "files/*.sh"
    - "files/Dockerfile"
  tags:
    - update-docker

- name: Generate an OpenSSH keypair
  community.crypto.openssh_keypair:
    path: /opt/bastion/sshpiper/id_rsa

- name: Copy docker bastion systemd file
  ansible.builtin.template:
    src: "docker-compose.service"
    dest: /etc/systemd/system/docker-compose@.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - Daemon reload

- name: Copy docker bastion
  ansible.builtin.template:
    src: "bastion-compose.j2"
    dest: /opt/bastion/docker/{{ item.name }}/docker-compose.yml
    owner: root
    group: root
    mode: '0644'
  with_items: "{{ user_list }}"
  register: service
  notify:
    - Restart unit
  tags: adduser

- name: Start docker bastion
  ansible.builtin.systemd:
    name: docker-compose@{{ item.name }}
    enabled: true
    state: started
  with_items: "{{ user_list }}"
  tags: adduser

- name: Copy docker sshpiper
  ansible.builtin.template:
    src: "sshpiper-compose.j2"
    dest: /opt/bastion/docker/sshpiper/docker-compose.yml
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart sshpiper
  tags: adduser

- name: Copy sshpiper config
  ansible.builtin.template:
    src: "sshpiper-config.yaml.j2"
    dest: /opt/bastion/sshpiper/sshpiper.yaml
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart sshpiper
  tags: adduser

- name: Start sshpiper
  ansible.builtin.systemd:
    name: docker-compose@sshpiper
    enabled: true
    state: started
