---
- name: Create docker directory
  ansible.builtin.file:
    path: /opt/bastion/docker/sshpiper
    state: directory
    mode: '0755'
    recurse: true

- name: Create sshpiper directory
  ansible.builtin.file:
    path: /opt/bastion/sshpiper
    state: directory
    mode: '0755'

- name: Copy docker file
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /opt/bastion/docker/{{ item | basename }}
    owner: root
    group: root
    mode: '0644'
  with_fileglob:
    - "files/*.sh"
    - "templates/Dockerfile"
  tags:
    - update-docker

- name: Copy proxy file
  ansible.builtin.template:
    src: "01proxy.j2"
    dest: /opt/bastion/docker/01proxy
  when: proxy_conf is defined

- name: Generate an OpenSSH keypair
  community.crypto.openssh_keypair:
    path: /opt/bastion/sshpiper/id_rsa
    owner: 1000

- name: Copy docker bastion systemd file
  ansible.builtin.template:
    src: "docker-compose.service"
    dest: /etc/systemd/system/docker-compose@.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - Daemon reload

- name: Copy docker sshpiper
  ansible.builtin.template:
    src: "sshpiper-compose.j2"
    dest: /opt/bastion/docker/sshpiper/docker-compose.yml
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart sshpiper

- name: Start sshpiper
  ansible.builtin.systemd:
    name: docker-compose@sshpiper
    enabled: true
    state: started
