---
- name: Copy sshpiper config
  ansible.builtin.template:
    src: "sshpiper-config.yaml.j2"
    dest: /opt/bastion/sshpiper/sshpiper.yaml
    owner: 1000
    group: 1000
    mode: '0600'
  notify:
    - Restart sshpiper
  tags: adduser

- name: Check user list
  ansible.builtin.find:
    paths: /var/log/bastion/
    recurse: no
    file_type: directory
  register: users
  tags: 
    - adduser
    - never

- name: User list OK
  no_log: true
  vars:
    userok: []
  set_fact:
    userok: "{{ userok + [item.path | basename] }}"
  with_items: "{{ users.files }}"
  tags: 
    - adduser
    - never

- name: Update user list
  no_log: true
  set_fact:
    user_list: "{{ user_list | reject('search', item) }}"
  with_items: "{{ userok }}"
  tags: 
    - adduser
    - never

- name: Create docker directory
  ansible.builtin.file:
    path: /opt/bastion/docker/{{ item.name }}
    state: directory
    mode: '0755'
  with_items: "{{ user_list }}"
  tags: adduser

- name: Create log directory
  ansible.builtin.file:
    path: /var/log/bastion/{{ item.name }}
    state: directory
    mode: '0755'
    owner: 1000
    group: 1000
  with_items: "{{ user_list }}"
  tags: adduser

- name: Create sshpiper user directory
  ansible.builtin.file:
    path: /opt/bastion/sshpiper/{{ item.name }}
    state: directory
    mode: '0700'
    owner: 1000
    group: 1000
  with_items: "{{ user_list }}"
  tags: adduser

- name: Create sshpiper user authorized_keys file
  ansible.builtin.copy:
    dest: /opt/bastion/sshpiper/{{ item.name }}/authorized_keys
    content: |-
      {{ item.key }}
    owner: 1000
    group: 1000
  with_items: "{{ user_list }}"
  tags: adduser

- name: Copy docker bastion
  ansible.builtin.template:
    src: "bastion-compose.j2"
    dest: /opt/bastion/docker/{{ item.name }}/docker-compose.yml
    owner: root
    group: root
    mode: '0644'
  with_items: "{{ user_list }}"
  register: service
  notify:
    - Restart unit
  tags: 
    - adduser
    - update-bastion

- name: slurp pub key
  slurp:
    src: /opt/bastion/sshpiper/id_rsa.pub
  register: slurp_remote_key
  tags: adduser

- name: Create user authorized_keys file
  ansible.builtin.copy:
    dest: /opt/bastion/docker/{{ item.name }}/authorized_keys
    content: |-
      {{ item.name }}:{{ slurp_remote_key['content'] | b64decode }}
    owner: 1000
    group: 1000
  with_items: "{{ user_list }}"
  tags: adduser

- name: Start docker bastion
  ansible.builtin.systemd:
    name: docker-compose@{{ item.name }}
    enabled: true
    state: started
  with_items: "{{ user_list }}"
  tags: adduser

