---
- name: Restart unit
  ansible.builtin.systemd:
    name: "docker-compose@{{ item.name }}"
    enabled: true
    state: restarted
    daemon_reload: true
    with_items: service.result

- name: Restart sshpiper
  ansible.builtin.systemd:
    name: docker-compose@sshpiper
    enabled: true
    state: restarted
    daemon_reload: true

- name: Daemon reload
  ansible.builtin.systemd:
    daemon_reload: true
