---
- name: Restart unit
  ansible.builtin.systemd:
    name: "docker-compose@{{ item }}"
    enabled: true
    state: restarted
    daemon_reload: true
  with_items: "{{ service.results | selectattr('changed', 'equalto', true) | map(attribute='item') | map(attribute='name') | list }}"

- name: Restart sshpiper
  ansible.builtin.systemd:
    name: docker-compose@sshpiper
    enabled: true
    state: restarted
    daemon_reload: true

- name: Restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted

- name: Daemon reload
  ansible.builtin.systemd:
    daemon_reload: true
