---
- name: Install prerequis
  apt: 
    name: apt-transport-https
    state: present

- name: User tasks
  include_tasks: users.yml
  tags: 
    - addadmin
    - deladmin
    - updatekey

- name: Rsyslog tasks
  include_tasks: rsyslog.yml
  tags: 
    - rsyslog
