---
- name: Create 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Add admin
  user:
    name: "{{ item }}"
    groups: wheel
    append: yes
    state: present
    createhome: yes
  with_items: "{{ admin_list.name }}"
  tags: addadmin

- name: Add authorized keys
  ansible.posix.authorized_key:
    user: "{{ item }}"
    key: "{{ lookup('file', 'files/'+ item + .pub') }}"
  with_items: "{{ admin_list.name }}"
  tags: 
   - addadmin
   - updatekey

- name: Retreive users
  shell: "getent passwd | awk -F: '{size=$3; if((size>=1000)&&(size<=2000)) {print $1}}'"
  register: users
  tags: deladmin

- name: Remove admin
  user:
    name: "{{item}}"
    state: absent
    remove: yes
  with_items: "{{ users.stdout_lines }}"
  when: item not in admin_list.name
  tags: deladmin
