---
- name: Install Docker
  ansible.builtin.apt:
    name: docker-ce
    state: present

- name: Configure Docker
  ansible.builtin.template:
    src: "daemon.json"
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart docker

- name: Ensure docker is running
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started
