---
- name: Add the GPG key for Docker
  apt_key:
    data: "{{ lookup('url', 'https://download.docker.com/linux/debian/gpg', split_lines=False) }}"
    state: present

- name: Add the repository to fetch the docker package
  apt_repository: 
    repo: deb https://download.docker.com/linux/debian bullseye stable
    state: present

- name: Create docker directory
  ansible.builtin.file:
    path: /var/lib/docker
    state: directory
    mode: '0755'
  run_once: true

- name: Mount docker volume
  shell: mount -a
  run_once: true

- name: Update source list and then install docker
  apt: 
    name: [docker-ce , docker-compose-plugin]
    state: present

- name: Configure Docker
  ansible.builtin.template:
    src: "daemon.json.j2"
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart docker

- name: Ensure docker is running
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started

- name: Add debian to docker group
  user:
    name: debian
    groups: docker
    append: yes
    state: present
