---
- name: Add the GPG key for Docker
  apt_key:
    data: "{{ lookup('url', 'https://download.docker.com/linux/debian/gpg', split_lines=False) }}"
    state: present

- name: Add the repository to fetch the docker package
  apt_repository: 
    repo: deb https://download.docker.com/linux/debian bullseye stable
    state: present

- name: Update source list and then install docker
  apt: 
    name: docker-ce 
    state: present

- name: Configure Docker
  ansible.builtin.template:
    src: "daemon.json.j2"
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart docker

- name: Ensure docker is running
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started
